name: Cypress project
on: [pull_request]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.2
        with:
          command: npm run cy:run

      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: index
          path: reports/cucumber-htmlreport.html
          retention-days: 30
